import localFont from "next/font/local";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat-header",
  weight: ["100", "300", "400", "500", "700", "800", "900"],
  preload: true,
});

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-body",
  weight: ["100", "300", "400", "500", "700", "900"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${roboto.variable} `}>
        <Navbar />
        {children}
        <Footer />
        <TailwindIndicator />
      </body>
    </html>
  );
}
